config:
  dockerfile: .woloxci/Dockerfile
  project_name: netcore-bootstrap

services:
  - postgres

steps:
  analysis:
    - ls -la
    - cd app
    - dotnet build

environment:
  GIT_COMMITTER_NAME: netcore-bootstrap
  GIT_COMMITTER_EMAIL: gustavo.siciliano@wolox.com.ar
  LANG: C.UTF-8
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
