config:
  dockerfile: .woloxci/Dockerfile
  project_name: netcore-bootstrap

services:
  - postgres

steps:
  analysis:
    - dotnet build

environment:
  GIT_COMMITTER_NAME: a
  GIT_COMMITTER_EMAIL: b
  LANG: C.UTF-8
